apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: svs-pubsub-asbtopic
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
  - name: connectionString 
    value: Endpoint=sb://xxxx.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=xxxxxx= 
